name: Definition of Done
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [edited]

jobs:
  check-dod:
    # Enable this check only when creating a new pull request
    # or when a comment of an open pull request gets edited
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      github.event.issue.state == 'open')
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Check DoD
        uses: platisd/definition-of-done@master
        with:
          dod_yaml: 'dod.yaml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
